# Generated by Django 4.2 on 2023-07-04 02:58

import IFCuida.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_vacinasadicionadas_delete_vacinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacinasadicionadas',
            name='motivo_rejeicao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vacinasadicionadas',
            name='comprovante',
            field=models.ImageField(upload_to=IFCuida.utils.GeradorNomeArquivo.gerar),
        ),
    ]
