# Generated by Django 4.2 on 2023-07-04 20:43

import IFCuida.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_questaoformsaude_respostaquestaoformsaude'),
        ('aluno', '0005_alter_vacinasadicionadas_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostaselecionadaformsaude',
            name='questao_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.questaoformsaude'),
        ),
        migrations.AlterField(
            model_name='respostaselecionadaformsaude',
            name='resposta_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.respostaquestaoformsaude'),
        ),
        migrations.AlterField(
            model_name='vacinasadicionadas',
            name='comprovante',
            field=models.ImageField(upload_to=IFCuida.utils.GeradorNomeArquivo.gerar),
        ),
    ]
