# Generated by Django 4.2 on 2023-07-10 20:59

import IFCuida.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0007_alter_vacinasadicionadas_comprovante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacinasadicionadas',
            name='comprovante',
            field=models.ImageField(upload_to=IFCuida.utils.GeradorNomeArquivo.gerar),
        ),
    ]
