# Generated by Django 4.2 on 2023-07-04 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestaoFormSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=100)),
                ('necessita_especificacao', models.BooleanField()),
                ('pre_requisito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.questaoformsaude')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaQuestaoFormSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=500)),
                ('pre_selecionada', models.BooleanField()),
                ('ativa_especificacao', models.BooleanField()),
                ('ativa_questao_dependente', models.BooleanField()),
                ('questao_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.questaoformsaude')),
            ],
        ),
    ]
